name: langchain_cli_examples
description: CLI examples for LangChain dart

environment:
  sdk: ^3.6.0

dependencies:
  langchain: ^0.8.0
  langchain_chroma: ^0.3.0
  langchain_community: ^0.4.0
  langchain_google: ^0.7.0
  langchain_ollama: ^0.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
