name: langchain_cli_examples
description: CLI examples for LangChain dart

environment:
  sdk: ^3.6.0

dependencies:
  langchain: ^0.7.8
  langchain_chroma: ^0.2.1+4
  langchain_community: ^0.3.3
  langchain_google: ^0.6.4+1
  langchain_ollama: ^0.3.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
