name: langchain_examples
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  langchain: ^0.7.7+1
  langchain_chroma: ^0.2.1+4
  langchain_community: ^0.3.3
  langchain_google: ^0.6.4+1
  langchain_ollama: ^0.3.2+1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0

workspace:
  - packages/cli
  - packages/apps/multi_modal
  - packages/shared

dependency_overrides:
  # Required override because:
  # - multi_modal depends on flutter_test which needs path 1.9.0
  # - langchain_community 0.3.3 needs path ^1.9.1
  # Temporary solution to resolve version conflict
  path: 1.9.1
